// article-publishing-platform/src/app/components/sidebar/sidebar.component.ts
import { Component, inject } from '@angular/core';
import { Router, RouterModule } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { AuthenticationService } from '../../services/authentication.service';
import { Store } from '@ngrx/store';
import { NgIf } from '@angular/common';

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [RouterModule,NgIf],
  templateUrl: './sidebar.component.html',
  styleUrl: './sidebar.component.css'
})
export class SidebarComponent {
  router = inject(Router);
  private authService = inject(AuthenticationService)
  store = inject(Store);
  current_userData: any
  ngOnInit(): void {
    //Called after the constructor, initializing input properties, and the first call to ngOnChanges.
    //Add 'implements OnInit' to the class.
    this.store.select('loggedUser').subscribe(data => {
      this.current_userData = data?.user;
      
    })

  }
  navigate(category: string) {
    this.router.navigate(['me', 'data', category])
  }

  logout() {
    const confirmMessage = `Are you sure you want to logout?`
    if (confirm(confirmMessage)) {
      this.authService.logout().subscribe(res => console.log(res))
    }
  }
}

<div class="flex h-screen flex-col lg:w-[18vw] justify-between border-e bg-white">
    <div class="px-4 py-6">
        <a routerLink="create-post"
            class="block rounded-lg cursor-pointer bg-gray-300 active::bg-emerald-200  text-gray-700 text-center px-4 py-2 text-sm font-medium hover:text-emerald-700">
            Publish Blog
        </a>

        <ul class="mt-6 space-y-1">
            <li>
                <a [routerLink]="['/']" [routerLinkActive]="'font-bold text-emerald-700 bg-emerald-200'"
                    [routerLinkActiveOptions]="{exact:true}"
                    class="block rounded-lg  px-4 py-2 text-sm font-medium text-gray-600 ">
                    Home
                </a>
            </li>

            <li>
                <details class="group [&_summary::-webkit-details-marker]:hidden">
                    <summary
                        class="flex cursor-pointer items-center justify-between rounded-lg px-4 py-2 text-gray-500 hover:bg-gray-100 hover:text-gray-700">
                        <span class="text-sm font-medium"> My Blogs </span>

                        <span class="shrink-0 transition duration-300 group-open:-rotate-180">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20"
                                fill="currentColor">
                                <path fill-rule="evenodd"
                                    d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                                    clip-rule="evenodd" />
                            </svg>
                        </span>
                    </summary>

                    <ul class="mt-2 space-y-1 px-4">
                        <li>
                            <a [routerLink]="['me','blogs','published']"
                                [routerLinkActive]="'font-bold text-emerald-700 bg-emerald-200'"
                                class="block rounded-lg px-4 py-2 text-sm font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-700">
                                Published
                            </a>
                        </li>

                        <li>
                            <a [routerLink]="['me','blogs','drafts']"
                                [routerLinkActive]="'font-bold text-emerald-700 bg-emerald-200'"
                                class="block rounded-lg px-4 py-2 text-sm font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-700">
                                Drafts
                            </a>
                        </li>
                        <li>
                            <a [routerLink]="['me','blogs','scheduled']"
                                [routerLinkActive]="'font-bold text-emerald-700 bg-emerald-200'"
                                class="block rounded-lg px-4 py-2 text-sm font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-700">
                                Scheduled
                            </a>
                        </li>
                    </ul>
                </details>
            </li>

            <li>
                <a routerLink="discover" [routerLinkActive]="'font-bold text-emerald-700 bg-emerald-200'"
                    class="block rounded-lg px-4 py-2 text-sm font-medium active:font-bold text-gray-500 ">
                    Discover
                </a>
            </li>

            <li>
                <a [routerLink]="['me','saved']" [routerLinkActive]="'font-bold text-emerald-700 bg-emerald-200'"
                    class="block rounded-lg px-4 py-2 text-sm font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-700">
                    Saved
                </a>
            </li>

            <li>
                <details class="group [&_summary::-webkit-details-marker]:hidden">
                    <summary
                        class="flex cursor-pointer items-center justify-between rounded-lg px-4 py-2 text-gray-500 hover:bg-gray-100 hover:text-gray-700">
                        <span class="text-sm font-medium"> Account </span>

                        <span class="shrink-0 transition duration-300 group-open:-rotate-180">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20"
                                fill="currentColor">
                                <path fill-rule="evenodd"
                                    d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                                    clip-rule="evenodd" />
                            </svg>
                        </span>
                    </summary>

                    <ul class="mt-2 space-y-1 px-4">
                        <li>
                            <a [routerLink]="['me','account']"
                                [routerLinkActive]="'font-bold text-emerald-700 bg-emerald-200'"
                                class="block rounded-lg px-4 py-2 text-sm font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-700">
                                Details
                            </a>
                        </li>
                        <li>
                            <div>
                                <button type="submit" (click)="logout()"
                                    class="w-full rounded-lg px-4 py-2 text-sm font-medium text-gray-500 [text-align:_inherit] hover:bg-gray-100 hover:text-gray-700">
                                    Logout
                                </button>
                            </div>
                        </li>
                    </ul>
                </details>
            </li>
        </ul>
    </div>

    <div class="sticky inset-x-0 bottom-0 border-t border-gray-100">
        <a href="#" class="flex items-center gap-2 bg-white p-4 hover:bg-gray-50">
            <img alt="" [src]="current_userData?.photoUrl" class="size-10 rounded-full object-cover" />

            <div>
                <p class="text-xs">
                    <strong class="block font-medium">{{current_userData?.displayName}}</strong>
                    <span class="text-ellipsis overflow-hidden"
                        *ngIf="current_userData?.email">{{current_userData?.email?.slice(0,23)}}.. </span>
                </p>
            </div>
        </a>
    </div>
</div>

// articles-app-react/src/components/Sidebar.jsx
import { Link, NavLink } from "react-router-dom";
function getNavLinkClasses({ isActive, isPending }) {
    const baseClasses =
        "block rounded-lg cursor-pointer px-4 text-gray-500 py-2 text-sm font-medium";
    const activeClasses = "bg-emerald-200 text-emerald-600";
    const pendingClasses = "text-gray-500 bg-gray-300";

    if (isActive) {
        return `${baseClasses} ${activeClasses}`;
    }
    if (isPending) {
        return `${baseClasses} ${pendingClasses}`;
    }
    return baseClasses;
}
export default function Sidebar() {

    return (
        <div className="px-4 py-6 flex flex-col max-h-screen max-w-[20vw] justify-center border-e bg-white">
            <div className="flex-1 py-2 w-full">
                <a className="px-4  block cursor-pointer rounded-lg py-2 bg-emerald-200 text-emerald-600 text-center text-sm font-medium">
                    Publish Blog
                </a>
            </div>
            <ul className="mt-6 space-y-1">
                <li>
                    <NavLink to={"/"} className={getNavLinkClasses}>Home</NavLink>
                </li>
                <li>
                    <details className="group [&_summary::-webkit-details-marker]:hidden">
                        <summary className="flex cursor-pointer items-center justify-between rounded-lg px-4 py-2 text-gray-500 hover:bg-gray-100 hover:text-gray-700">
                            <span className="text-sm font-medium"> My Blogs </span>

                            <span className="shrink-0 transition duration-300 group-open:-rotate-180">
                                <svg
                                    xmlns="http://www.w3.org/2000/svg"
                                    className="h-5 w-5"
                                    viewBox="0 0 20 20"
                                    fill="currentColor"
                                >
                                    <path
                                        fillRule="evenodd"
                                        d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                                        clipRule="evenodd"
                                    />
                                </svg>
                            </span>
                        </summary>

                        <ul className="mt-2 space-y-1 px-4">
                            <li>
                                <NavLink to={"/me/blogs/published"} className={getNavLinkClasses}>Published</NavLink>
                            </li>

                            <li>
                                <NavLink to={"/me/blogs/drafts"} className={getNavLinkClasses}>Drafts</NavLink>
                            </li>
                            <li>
                                <NavLink to={"/me/blogs/scheduled"} className={getNavLinkClasses}>Scheduled</NavLink>
                            </li>
                        </ul>
                    </details>
                </li>

                <li>
                    <NavLink to={"/discover"} className={getNavLinkClasses}>Discover</NavLink>
                </li>

                <li>
                    <NavLink to={"/me/blogs/saved"} className={getNavLinkClasses}>Saved</NavLink>
                </li>

                <li>
                    <details className="group [&_summary::-webkit-details-marker]:hidden">
                        <summary className="flex cursor-pointer items-center justify-between rounded-lg px-4 py-2 text-gray-500 hover:bg-gray-100 hover:text-gray-700">
                            <span className="text-sm font-medium"> Account </span>

                            <span className="shrink-0 transition duration-300 group-open:-rotate-180">
                                <svg
                                    xmlns="http://www.w3.org/2000/svg"
                                    className="h-5 w-5"
                                    viewBox="0 0 20 20"
                                    fill="currentColor"
                                >
                                    <path
                                        fillRule="evenodd"
                                        d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                                        clipRule="evenodd"
                                    />
                                </svg>
                            </span>
                        </summary>

                        <ul className="mt-2 space-y-1 px-4">
                            <li>
                                <NavLink to={"/me/account"} className={getNavLinkClasses}>Account</NavLink>
                            </li>
                            <li>
                                <div>
                                    <button
                                        type="submit"
                                        className="w-full rounded-lg cursor-pointer px-4 py-2 text-sm font-medium text-gray-500 [text-align:_inherit] hover:bg-gray-100 hover:text-gray-700"
                                    >
                                        Logout
                                    </button>
                                </div>
                            </li>
                        </ul>
                    </details>
                </li>
            </ul>
        </div>
    );
}
