// article-publishing-platform/src/app/pages/home/home.component.ts
import { Component, inject } from '@angular/core';
import { ArticleCardComponent } from "../../components/article-card/article-card.component";
import { FeaturedComponent } from "../../components/featured/featured.component";
import { BLOGS } from '../../services/blogs';
import { NgClass, NgFor } from '@angular/common';
import { interval, map, timer } from 'rxjs';
import { ArticleServiceService } from '../../services/article-service.service';
import { FormsModule } from '@angular/forms';
import { Store } from '@ngrx/store';
import { OnlinePublishingService } from '../../services/online-publishing.service';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [ArticleCardComponent, FeaturedComponent, NgFor, NgClass, FormsModule],
  templateUrl: './home.component.html',
  styleUrl: './home.component.css'
})
export class HomeComponent {
  popular_blogs: any;
  selectedId: string = '';
  currentFeaturedBlog: any
  source$ = timer(0, 5000);
  pageSize = 5;
  currentPage = 1;
  totalPages = 0;
  currentItems: any = []
  articleService = inject(OnlinePublishingService)
  store = inject(Store);
  currentuser: any
  ngOnInit(): void {
    this.getArticles()
  }
  getArticles() {
    this.store.select('loggedUser').subscribe(data => {
      console.log(data);
      
      if (data?.user) {
        this.currentuser = data?.user
        this.articleService.getAllArticles().subscribe(data => {
          console.log(data);
          
          this.popular_blogs = data
          this.totalPages = Math.ceil(this.popular_blogs.length / this.pageSize);
          this.loadItems()
          // todo 
            // pick based on most viewed and most commented...
          this.source$.pipe(
            map(() => this.popular_blogs?.[Math.floor(Math.random() * this.popular_blogs?.length)]),
          ).subscribe(data => {
            this.currentFeaturedBlog = data
          })
        })
      }
    })

  }
  greet() {
    const time = new Date();
    const hours = time.getHours();
    if (hours < 12) {
      return `Good Morning`
    } else if (hours < 18) {
      return 'Good Afternoon'
    } else {
      return 'Good Evening'
    }
  }

  loadItems() {
    const start = (this.currentPage - 1) * this.pageSize;
    const end = start + this.pageSize;
    this.currentItems = this.popular_blogs.slice(start, end);
  }

  previousPage() {
    if (this.currentPage > 1) {
      this.currentPage--;
      this.loadItems();
    }
  }

  nextPage() {
    if (this.currentPage < this.totalPages) {
      this.currentPage++;
      this.loadItems();
    }
  }
  getToValue() {
    return Math.min(this.currentPage * this.pageSize, this.popular_blogs?.length)
  }
}

<div>
    <p class="font-medium text-xl text-gray-800">{{greet()}} {{currentuser?.displayName}}</p>
    <div class="py-4">
        <div class="mb-4">
            <app-featured [featuredData]="currentFeaturedBlog" />
            <div class="flex gap-1 justify-center py-2">
                <div [ngClass]="item._id==currentFeaturedBlog?._id?'bg-emerald-400':'bg-gray-400 '"
                    *ngFor="let item of popular_blogs?.slice(0,3)" (click)="currentFeaturedBlog = item"
                    class="w-3.5 h-3.5 border-2 border-white cursor-pointer dark:border-gray-800 rounded-full"></div>
            </div>
        </div>

        <div class="flex justify-between items-center">
            <div>
                <p class="text-gray-600 text-sm">Showing {{(currentPage - 1) * pageSize + 1 }} to {{ getToValue()}}
                    Articles of {{popular_blogs?.length}} </p>
            </div>
            <div class="flex gap-4 items-center">
                <div class="-mt-6">
                    <label for="HeadlineAct" class="block text-sm font-medium text-gray-900"> Sort By </label>

                    <select name="HeadlineAct" id="HeadlineAct"
                        class="mt-1.5 w-full rounded-lg border-gray-300 text-gray-700 sm:text-sm">
                        <option value="">Please select</option>
                        <option value="JM">Most Recent</option>
                        <option value="SRV">Oldest</option>
                        <option value="JH">Popular</option>
                        <option value="JH">Editor's Pick</option>
                    </select>
                </div>
                <div class="flex justify-end gap-1">
                    <a (click)="previousPage()" [class.disabled]="currentPage === 1"
                        class="inline-flex size-8 cursor-pointer items-center justify-center rounded border border-gray-300 bg-white text-gray-900 rtl:rotate-180 dark:border-gray-800 dark:bg-gray-900 dark:text-white">
                        <span class="sr-only">Prev Page</span>
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-3 w-3" viewBox="0 0 20 20" fill="currentColor">
                            <path fill-rule="evenodd"
                                d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z"
                                clip-rule="evenodd" />
                        </svg>
                    </a>

                    <div>
                        <label for="PaginationPage" class="sr-only">Page</label>

                        <input type="number" disabled
                            class="h-8 w-12 rounded border border-gray-300 bg-white p-0 text-center text-xs font-medium text-gray-900 [-moz-appearance:_textfield] dark:border-gray-800 dark:bg-gray-900 dark:text-white [&::-webkit-inner-spin-button]:m-0 [&::-webkit-inner-spin-button]:appearance-none [&::-webkit-outer-spin-button]:m-0 [&::-webkit-outer-spin-button]:appearance-none"
                            min="1" [value]="currentPage" id="PaginationPage" />
                    </div>

                    <a (click)="nextPage()" [class.disabled]="currentPage >= totalPages"
                        class="inline-flex size-8 cursor-pointer items-center justify-center rounded border border-gray-300 bg-white text-gray-900 rtl:rotate-180 dark:border-gray-800 dark:bg-gray-900 dark:text-white">
                        <span class="sr-only">Next Page</span>
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-3 w-3" viewBox="0 0 20 20" fill="currentColor">
                            <path fill-rule="evenodd"
                                d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                                clip-rule="evenodd" />
                        </svg>
                    </a>
                </div>
            </div>
        </div>
       
    </div>
    
</div>

// articles-app-react/src/pages/Home.jsx
import { useState } from "react";
import FeatureCard from "../components/FeatureCard";
import ArticleCard from "../components/articleCard";
import useGetArticles from "../hooks/useGetArticles";
function Home() {
  const articles = useGetArticles("articles");
  const [userName] = useState("Sumanth");
  const randomArticle = Math.floor(Math.random() * articles?.length + 1);
  const [currentPage,setCurrentPage] = useState(1);
  const articlesPerPage = 3;
  
  return articles.length === 0 ? (
    <div>Loading Data.....</div>
  ) : (
    <div>
      <p className="font-medium text-lg text-gray-700">
        Good Morning {userName}
      </p>
      <div className="my-2">
        <h2 className="font-medium text-base text-gray-600 ">
          Popular Articles
        </h2>
        <FeatureCard data={articles[randomArticle]} />
      </div>
      <div className="flex justify-end gap-1">
        <a className="inline-flex size-8 cursor-pointer items-center justify-center rounded border border-gray-300 bg-white text-gray-900 rtl:rotate-180 dark:border-gray-800 dark:bg-gray-900 dark:text-white">
          <span className="sr-only">Prev Page</span>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            className="h-3 w-3"
            viewBox="0 0 20 20"
            fill="currentColor"
          >
            <path
              fillRule="evenodd"
              d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z"
              clipRule="evenodd"
            />
          </svg>
        </a>

        <div>
          <label htmlFor="PaginationPage" className="sr-only">
            Page
          </label>

          <input
            type="number"
            disabled
            className="h-8 w-12 rounded border border-gray-300 bg-white p-0 text-center text-xs font-medium text-gray-900 [-moz-appearance:_textfield] dark:border-gray-800 dark:bg-gray-900 dark:text-white [&::-webkit-inner-spin-button]:m-0 [&::-webkit-inner-spin-button]:appearance-none [&::-webkit-outer-spin-button]:m-0 [&::-webkit-outer-spin-button]:appearance-none"
            min="1"
            id="PaginationPage"
          />
        </div>

        <a className="inline-flex size-8 cursor-pointer items-center justify-center rounded border border-gray-300 bg-white text-gray-900 rtl:rotate-180 dark:border-gray-800 dark:bg-gray-900 dark:text-white">
          <span className="sr-only">Next Page</span>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            className="h-3 w-3"
            viewBox="0 0 20 20"
            fill="currentColor"
          >
            <path
              fillRule="evenodd"
              d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
              clipRule="evenodd"
            />
          </svg>
        </a>
       
      </div>

      <div className="my-2">
        {articles.map((article) => (
          <div className="py-2" key={article._id}>
            <ArticleCard data={article} />
          </div>
        ))}
      </div>
    </div>
  );
}

export default Home;
